# AnVIL Module Library

There are several pieces of content that are useful across multiple books, such as "How to Create a Workspace".  To reduce maintenance burden, the `AnVIL_Template` repository has a collection of `_child` R Markdown documents that can be included in your books.

You can see all the available AnVIL modules in the [AnVIL_Template book](https://jhudatascience.org/AnVIL_Template/)

## Include using `cow::borrow_chapter()`

To add a module to your book, include a code chunk with the `cow::borrow_chapter()` function, specifying the file for the module you want to borrow and the repository you want to borrow it from (the `AnVIL_Template` repository).

See the OTTR_Template [wiki page](https://github.com/jhudsl/OTTR_Template/wiki/Borrowing-chapters-between-courses) for the most recent instructions and additional details.

Here is an example of including the `_child_workspace_create.Rmd` with `cow::borrow_chapter()`

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "child/_child_workspace_create.Rmd",
  repo_name = "jhudsl/AnVIL_Template"
)
```

